### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by the2pizza** [nezavisimost/FuckRKN1#1]

**Comment by SDesya74** [comment]
![изображение](https://user-images.githubusercontent.com/41489405/173903010-820ac884-f027-4c9f-9164-9d61fb672305.png)

?

**Comment by nizhgo** [comment]
![FUCKRNK1](https://user-images.githubusercontent.com/51023341/173919216-d7df810c-2801-4b55-9500-40d6b0d2603a.png)
![FUCKRNK1_white](https://user-images.githubusercontent.com/51023341/173919423-b740e3e0-55be-41bb-b824-144399791df2.png)

**Comment by Max-Tetslav** [comment]
![fuckRkn1](https://user-images.githubusercontent.com/63692030/173925884-8f4ae27d-381f-44e5-9a2b-bdd5eab25225.svg)
![fuckRkn1_white](https://user-images.githubusercontent.com/63692030/173926267-de4a89cc-d83a-4ca4-bb03-72ad800947da.svg)

**Comment by Erghel** [comment]
Видимо, одно из обязательных условий Logo - Птеродактиль. А вообще лого, представленные выше, очень классные.

**Comment by the2pizza** [comment]
![photo_2022-06-16 02 22 39](https://user-images.githubusercontent.com/6414316/174029929-cf9bfe63-14e5-4993-a61c-9c49175fb3de.jpeg)
