### ISSUE TITLE
[FEAT]: Add instructions on how to extract .p12 keys

### ISSUE THREAD

**Issue by glotov4** [nezavisimost/FuckRKN1#107]
### Description

When I try to extract keys from .p12, "import' button is inactive and on hover it says "Cannot import because there are no compatible importers"
Can you please add information on how to handle it in Linux instructions?
I'm using Xubuntu
Linux 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022 x86_64 GNU/Linux

### Additional Information

![image](https://user-images.githubusercontent.com/98843804/190625336-a109580b-1fd5-48eb-a80f-017f16840640.png)

**Comment by megre4ka** [comment]
hi. use terminal.
In terminal command: cd /home/*username*/Downloads (if u don't transfer .p12 to another directory) & Enter
And after use this all command in terminal: 
openssl pkcs12 -in vpnclient.p12 -cacerts -nokeys -out ikev2vpnca.cer
openssl pkcs12 -in vpnclient.p12 -clcerts -nokeys -out vpnclient.cer
openssl pkcs12 -in vpnclient.p12 -nocerts -nodes  -out vpnclient.key
rm vpnclient.p12

sudo chown root.root ikev2vpnca.cer vpnclient.cer vpnclient.key
sudo chmod 600 ikev2vpnca.cer vpnclient.cer vpnclient.key

that's all Folks

**Comment by theyllneverfindyourgrave** [comment]
We already have these instructions. 
![image](https://user-images.githubusercontent.com/107606096/192565631-4bb36be5-dc43-471d-9efb-39928524c5ec.png)
