### ISSUE TITLE
Seems that Windows VPN connection is down today.

### ISSUE THREAD

**Issue by archhaze24** [nezavisimost/FuckRKN1#108]
### Description of the bug

Every time I'm trying to connect to VPN on Windows, it gives me this error: 
![Screenshot_16](https://user-images.githubusercontent.com/49359990/192099737-25b3212f-2303-4d1f-a1e2-11da79877886.png)
![Screenshot_17](https://user-images.githubusercontent.com/49359990/192099742-6486b4cb-4463-466b-92a4-facd667e5fc4.png)
Althrough on Linux everything works fine.
Also this issue occurs to all people who I know now.
Reinstalling the VPN haven't solved this issue.

### Steps To Reproduce

1. Try to connect to VPN on Windows

**Comment by theyllneverfindyourgrave** [comment]
I think hoster turned off a few servers, now they're working. Next time you can see if they're down on our dashboard. 
https://m.fuckrkn1.org/d/fX0pLFiVz/fuckrkn1-dashboard?orgId=1&from=now-1h&to=now
