### ISSUE TITLE
[BUG]: Private key decryption password required to establish VPN connection

### ISSUE THREAD

**Issue by archhaze24** [nezavisimost/FuckRKN1#124]
### Description of the bug

After setting up vpn on Fedora Linux, I get this prompt:
![image](https://user-images.githubusercontent.com/49359990/198899483-8877808d-ba85-492c-aec4-9bb5faae1cc9.png)
I tried installing vpn with script and manually (Lithuania servers).

### Steps To Reproduce

1. Follow Linux installation instructions.
2. Try to connect to vpn.

### Additional Information

Edit: looks like this issue is duplicate of #49.

**Comment by ndrws** [comment]
https://github.com/nezavisimost/FuckRKN1/issues/127#issue-1431841146 

https://bugzilla.redhat.com/show_bug.cgi?id=1932473

**Comment by archhaze24** [comment]
> [#127 (comment)](https://github.com/nezavisimost/FuckRKN1/issues/127#issue-1431841146)
> 
> https://bugzilla.redhat.com/show_bug.cgi?id=1932473

Спасибо, ваш фикс сработал. Думаю тогда стоит добавить этот фикс в гайд по установке для Linux и в скрипт для автоустановки.

**Comment by archhaze24** [comment]
Closing this issue because #128 gives an instruction how to solve it.
