### ISSUE TITLE
[BUG]: RU config doesn't work

### ISSUE THREAD

**Issue by dangreen** [nezavisimost/FuckRKN1#134]
### Description of the bug

RU config doesn't work

https://github.com/nezavisimost/FuckRKN1/blob/main/client-conf/ru-vpnclient.mobileconfig

<img width="416" alt="Снимок экрана 2023-04-23 в 14 06 32" src="https://user-images.githubusercontent.com/986756/233833378-57b29701-1f1a-44a2-b372-cd4a0ce65caa.png">

Tested on macOS and iOS. IT config is working.

### Steps To Reproduce

1. Install ru profile
2. Try to connect

**Comment by theyllneverfindyourgrave** [comment]
we don't have russian servers on IPSec anymore, try WireGuard https://fuckrkn1.org/installation-ru.html
