### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by the2pizza** [nezavisimost/FuckRKN1#2]
How to configure for dummies

- windows
- macos
- iOs
- Andorid
- Linux

**Comment by bogdanmirz** [comment]
> > I suggest making it in Notion at first. I believe it will be quite enough comfy and user-friendly for both contributors and end users. My experience says that Notion is nearly superb for up to 5 contributors and is allright for around 10 editors.
> > I guess trial version of Notion will be capable for the job. It might be organized as prod and stage pages of docs, where prod is public, and stage is members. The stage credentials may be shared within repo admin/editing team
> > comments?
> 
> I think configuration should be described on site and in git only, as it not should be hard to understand. So in summ we make manuals here may be in separate folder and in MarkDown format

I agree with .md and git, that was my very first thought actually. But what about screenshots in those manuals? It's not really user-friendly to cope with them in .md

**Comment by grund1k** [comment]
> > > I suggest making it in Notion at first. I believe it will be quite enough comfy and user-friendly for both contributors and end users. My experience says that Notion is nearly superb for up to 5 contributors and is allright for around 10 editors.
> > > I guess trial version of Notion will be capable for the job. It might be organized as prod and stage pages of docs, where prod is public, and stage is members. The stage credentials may be shared within repo admin/editing team
> > > comments?
> > 
> > 
> > I think configuration should be described on site and in git only, as it not should be hard to understand. So in summ we make manuals here may be in separate folder and in MarkDown format
> 
> I agree with .md and git, that was my very first thought actually. But what about screenshots in those manuals? It's not really user-friendly to cope with them in .md

Aside from .md and git, it will be a good idea to make short video guides. I think it will be user-friendly as well. 

Common user prefer to install VPN with one button. I don`t think that most of them will like to read docs.

**Comment by bogdanmirz** [comment]
noboby reads the docs, but they need to exist anyway :)

so, let me try to sum it up as a draft. 

- We start with Notion while we need to make a llot of changes. 
- Then copy it to repo in .md. 
- Finally create screencast of it on Youtube. RUS + ENG
     - Probably with subtitles.

**Comment by Erghel** [comment]
Было бы неплохо записать короткие видеоролики с настройкой strongSwan для каждой платформы и залить их потом на сайт.

Идея взята из сервиса xeovo.

**Comment by bogdan0083** [comment]
We should fix typo in About section: speach -> speech:

<img src="https://img001.prntscr.com/file/img001/DRqh2dmdS--ug3IceIlCaA.png" />

Not a big deal but still catches the eye :)
