### ISSUE TITLE
Linux client, need to add ability to connect via IKEv2 (sswan) via network manager

### ISSUE THREAD

**Issue by er2805620** [nezavisimost/FuckRKN1#35]
Need to update /etc/ipsec.d/ikev2.conf

```
conn ikev2-cp
...
  authby=rsa-sha1
```  
and 

```
service ipsec restart
```
As we don't know how /etc/ipsec.d/ikev2.conf look currently we can't attach full file for template and can't update prepare/update script for setup/upgrade

from https://github.com/hwdsl2/setup-ipsec-vpn

Before configuring Linux VPN clients, you must make the following change on the VPN server: Edit /etc/ipsec.d/ikev2.conf on the server. Append authby=rsa-sha1 to the end of the conn ikev2-cp section, indented by two spaces. Save the file and run service ipsec restart.

**Comment by theyllneverfindyourgrave** [comment]
we already discussed this, will be done on the new servers

**Comment by the2pizza** [comment]
Added for new servers

**Comment by er2805620** [comment]
where list of new servers for check? Once it will be checked I can update manual for Linux

**Comment by the2pizza** [comment]
Now we have dns-load balancer and you can use one name now - lt.fuckrkn1.xyz
