### ISSUE TITLE
Add-VpnConnection : Не удается подключиться к CIM-серверу. Неправильное пространство имен

### ISSUE THREAD

**Issue by memUsins** [nezavisimost/FuckRKN1#46]
https://user-images.githubusercontent.com/83538724/177292610-3521a4a3-9a99-4107-a16e-eb07b469e558.mp4

Делаю всё чётко по инструкции. Файл разблокировал, от администратора запустил. Шаг за шагом следовал по праведному пути readme файла, но вместо заветного коннекта выдаёт ошибку пространства имён. Не понимаю, в чём проблема и как её решить. 

Система:
![image](https://user-images.githubusercontent.com/83538724/177293016-d29a308c-29d5-436f-ba8b-842aeea98eba.png)

На win 10 на той же сети всё отлично работает и коннектится, на 11 — не хочет.

**Comment by memUsins** [comment]
Пытался, сперва так и делал, но в видео указал именно процесс вставки, чтобы отпали вопросы об ошибке в адресе.

**Comment by theyllneverfindyourgrave** [comment]
запиши пожалуйста полный видос, чтобы было видно папку, как скрипт запускаешь

**Comment by memUsins** [comment]
![image](https://user-images.githubusercontent.com/83538724/177591565-94ffd1a5-7937-4c96-805a-2ed96e5ace41.png)
Ну, по видимому, да.

**Comment by memUsins** [comment]
![image](https://user-images.githubusercontent.com/83538724/177993889-093d3fc9-2da1-4c36-be95-96369821af1d.png)

Не сильно что-то изменилось. Пробовал напрямую подключаться через панель виндовс, но толку никакого. Попробовал с ноута тоже на 11 винде, подключилось сразу же. Быть может, какая-то аппаратная ошибка? В драйверах дело?

**Comment by memUsins** [comment]
![image](https://user-images.githubusercontent.com/83538724/177995821-ecff9728-f295-435f-96f7-3fb3e0b124bb.png)
Ошибка, как я понимаю, именно в этом (в cmd файле порылся, решил напрямую итоговые скрипты запустить).

**Comment by memUsins** [comment]
Обновил powershell с 5.1 до 7.2
Теперь просто подобное отдаёт
![image](https://user-images.githubusercontent.com/83538724/177998109-b33a4dd0-e794-4f5b-8e69-38a3b403f159.png)

**Comment by theyllneverfindyourgrave** [comment]
почему закрыл?

**Comment by memUsins** [comment]
Проблема пока не решилась, решения тоже не ищутся, играюсь с другими устройствами в доме и пока на них всё работает, проблема лишь на основном компе. Гугл пока толкового ничего не выдаёт. 

Пока решений не предвидится, думаю, попробую поиграться с роутером (раздаю с телефона на комп, с компа на роутер, в глухой деревне живу, где о кабельном интернете и не слышали). Там, вроде, всё работает, буду, получается, пытаться сразу раздавать с подключенным впн-ом на роутер, раз на компе не заводится. 

Ишью повторно, если ничего не получится, открою (инет тупанул, потому сперва закрылось, потом отправилось верхнее сообщение), думаю, я пока единичный случай с подобной ошибкой.

**Comment by theyllneverfindyourgrave** [comment]
я тоже ничего не нагуглил :( 
а битность системы и powershell совпадает?

**Comment by memUsins** [comment]
Да, с самого начала проверил это. Несколько раз переустанавливал powershell, устанавливал все обновления винды, сверху, чисто для галочки, решил обновить V++, но тоже толку никакого не дало. А так, первые страниц 5 по запросу прошарил, но толком ничего не дало

**Comment by memUsins** [comment]
Доброго времени суток всем ещё раз. Проблему решил. Решал не её, но, как в последствии выяснилось, её тоже коснулось. Нужно было всего лишь перезапустить службу **winmgmt**. Вот, что выполнял:

```
sc config winmgmt start=disabled
net stop winmgmt
Winmgmt /salvagerepository %windir%\System32\wbem
Winmgmt /resetrepository %windir%\System32\wbem
sc config winmgmt start=auto
```

Информацию брал отсюда — https://stackoverflow.com/a/72505247. Вопрос из другой темы, так как решал подобную проблему с докером. Всем спасибо, все молодцы.
