### ISSUE TITLE
fedora linux decryption password

### ISSUE THREAD

**Issue by theyllneverfindyourgrave** [nezavisimost/FuckRKN1#49]
requires password to connect on fedora

**Comment by ttldtor** [comment]
The same for Ubuntu 22.04
![image](https://user-images.githubusercontent.com/3264871/179014861-383d5cc5-0b93-471b-87c3-1f25ae8732d9.png)

**Comment by er2805620** [comment]
more info please, also did you try any password like 111111?

**Comment by EtoMisha** [comment]
Same thing on Ubuntu 20.04.4 LTS
Message when trying to turn on:
Private key decryption password required to establish VPN connection 'FuckRKN'
Passwords like 111111 or something don't help

**Comment by megre4ka** [comment]
OS: Linux fedora 5.19.6-200.fc36.x86_64
Strongswan version: Linux strongSwan U5.9.6/K5.19.6-200.fc36.x86_64
VPN config: 
![image](https://user-images.githubusercontent.com/110228157/189213014-1cd80926-afa5-4818-b8e1-cfa5d5f05df9.png)
When try to connect:  
![image](https://user-images.githubusercontent.com/110228157/189213285-03dcb5fe-72ec-4ff7-81c4-62d0a8648745.png)
Passwords like: '111111','123456' don't help.

**Comment by archhaze24** [comment]
Fix for this issue can be found in #127.
