### ISSUE TITLE
Vpn client windows

### ISSUE THREAD

**Issue by the2pizza** [nezavisimost/FuckRKN1#54]

**Comment by RomanBaukin** [comment]
https://user-images.githubusercontent.com/65417719/180951792-80d6a537-65d8-40cc-8d28-3dcc14234015.mp4

After running as administrator, the terminal window opens and immediately closes.

OS: Windows 10 Home v.21H2

**Comment by RomanBaukin** [comment]
https://user-images.githubusercontent.com/65417719/180953273-52db0f1e-4477-4517-85ee-60ed52e8a1a4.mp4

After running as administrator, the terminal window opens and immediately closes.

OS: Windows 10 Home v. 21H2

**Comment by HotFixDeveloper** [comment]
Project Repository - https://github.com/nezavisimost/liberty-win

**Comment by the2pizza** [comment]
Moved to  https://github.com/nezavisimost/liberty-win
