### ISSUE TITLE
Vpn client iOS

### ISSUE THREAD

**Issue by the2pizza** [nezavisimost/FuckRKN1#55]

**Comment by Nea88** [comment]
First create repo and add me to maintain

**Comment by Nea88** [comment]
Simple UX design needed

**Comment by HotFixDeveloper** [comment]
Also we have screencast 

https://twitter.com/i/status/1552986197135446016

**Comment by HotFixDeveloper** [comment]
Project Repository - https://github.com/nezavisimost/liberty-ios

**Comment by the2pizza** [comment]
Moved to  https://github.com/nezavisimost/liberty-ios
