### ISSUE TITLE
Oculus quest 2 install guide

### ISSUE THREAD

**Issue by phatal** [nezavisimost/FuckRKN1#57]
Привет, добавьте гайд по использованию fuckrkn1 vpn на oculus quest 2 пожалуйста, т.к. девайс завязан на сервисы Meta то сейчас использование VPN это единственный способ полноценно его использовать, а  сам процесс не самый очевидный. Так как oq2 (oculus quest 2) работает под управлением OS основанной на Android 10 то и процесс установки похожий, но с некоторыми нюансами.
Шаги установки :
1) Необходимо активировать developer mode на oq2 что бы можно было устанавливать приложения самостоятельно, гайд по активации с офф. сайта: ([https://developer.oculus.com/documentation/native/android/mobile-device-setup/](url))
2) Теперь когда мы можем устанавливать сторонние приложения (так называемый sideloading) нам необходимо перенести на шлем файл vpnclient.sswan (по аналогии с установкой на android). Это можно сделать через встроенный в шлем браузер либо используя adb, скачиваем файл на пк и пушим его на шлем:
`adb push vpnclient.sswan /sdcard/`
3) Следующим шагом установим strong swan скачав apk с [https://download.strongswan.org/Android/](url) и установив его на шлем командой:
`adb install -g -r strongSwan-2.3.3.apk`

И вот теперь казалось бы можно надеть шлем и повторить шаги с андройда но есть одна хитрость. По умолчанию встроенный файловый менеджер достаточно урезан и при нажатии на "import vpn profile" просто ничего не произойдет (по аналогичной причине strong swan устанавливается через adb) поэтому переходим к следующему шагу

4) Скачиваем и устанавливаем кастомный file manager, например Mixplorer (у меня установлен он) с 4pda :
[https://4pda.to/forum/index.php?showtopic=318294](url)
и устанавливаем его командой
`adb install -g -r mixplorer.apk`

Теперь можно надеть шлем и оставшиеся шаги повторить как при установке на anroid т.к. теперь по нажатию на "import VPN profile" для навигации и выбора файла будет использоваться mixplorer.

**Comment by the2pizza** [comment]
Done
