### ISSUE TITLE
[Landing] Page with instructions 

### ISSUE THREAD

**Issue by the2pizza** [nezavisimost/FuckRKN1#62]
Короче котятки, у нас сейчас ссылка инструкции  идёт на гитхаб, а по-хорошему надо бы чтоб никаких переходов не было на другие сайты и инстуркции были отдельной страничкой вместе с видосиками и скачиванием файлов, а то настраивать по гитхабу даже мне больно, не говоря уже про людей кто гх в первый раз видит.

**Comment by romanlesnoy** [comment]
Привет! 
Я возьмусь за верстку лэндинга?

**Comment by romanlesnoy** [comment]
#80 
Добавил русскоязычную версию инструкций

**Comment by the2pizza** [comment]
> #80 Добавил русскоязычную версию инструкций

@romanlesnoy ждём англ версию. И можно будет мерджить

**Comment by romanlesnoy** [comment]
Хорошо, доберусь вечером до компьютера, и отправлю пул реквест

**Comment by the2pizza** [comment]
Done - https://github.com/nezavisimost/FuckRKN1/pull/80
