### ISSUE TITLE
[Infra] Put configuration files to a server 

### ISSUE THREAD

**Issue by the2pizza** [nezavisimost/FuckRKN1#65]
Need to run nginx as fileserver, github is shitty as fuck for distributing config files

**Comment by er2805620** [comment]
@the2pizza 
what OS 
what place on filesystem for files? like /home/user/files/certificate.p12
and what URI should have setting files? like domainame.com/configs/certificate.p12

**Comment by the2pizza** [comment]
@er2805620 

1. Not sure I got the question, I meant we need a place which we can provide as more comfortable way to download the files behind github web-interface 
2. I already bought the server s.fuckrkn1.xyz; fuckrkn1.org is already hosted on gh pages ._.

**Comment by er2805620** [comment]
1) yes I understand but need more info to do config

As i understand domain will be
s.fuckrkn1.xyz
also we need to install certbot for letsencrypt certs 
we need to know place where you store certificates on s.fuckrkn1.xyz to download
and create pipeline where certs on the s.fuckrkn1.xyz will be automatically replaced if it changed on github

and we can just use link to raw file not to the github

https://github.com/nezavisimost/FuckRKN1/raw/main/client-conf/vpnclient.p12
example:
[vpnclient.p12](https://github.com/nezavisimost/FuckRKN1/raw/main/client-conf/vpnclient.p12)

**Comment by the2pizza** [comment]
Done

https://s.fuckrkn1.xyz

https://github.com/nezavisimost/FuckRKN1/pull/83
