### ISSUE TITLE
[Doc] Instruction how to configure Linux via console

### ISSUE THREAD

**Issue by the2pizza** [nezavisimost/FuckRKN1#67]
Через консоль настройка на линуксах должна быть надежнее чем через кучу разных нетворк менеджеров с гуём. 

Возможно сделать скрипт который упростит настройку?

**Comment by the2pizza** [comment]
> no network-manager is good choice here as
> 
>     * we need VPN on desktop not on the server
> 
>     * different settings for different OS (debain/RH/Arch family as minimum)

what's the problem to handle these differencies? 

Network Managers are different even for different Window Environments

**Comment by er2805620** [comment]
>>Network Managers are different even for different Window Environments
not really, basically this is the same package, compiled for different DE
but also another one issue if it not the NetworkManager we should do script for
- systemd-networkd
- netctl
- standalone strongswan+charon config
and test it as minimum on Ubuntu/Fedora/Arch

it not hard to do this, but no sense as who have ability to do this just do it but low-skill users will be have lot of issues.

**Comment by theyllneverfindyourgrave** [comment]
now we have a command to install through terminal
