### ISSUE TITLE
vpn .p12 file

### ISSUE THREAD

**Issue by am-i-dead** [nezavisimost/FuckRKN1#8]
need to generate vpnclient.p12 for Windows and Linux users

**Comment by deviousway** [comment]
p12 it key format. not the openvpn setting format. Do you mean .ovpn ?
For my understanding it should be just ovpn and keys should be inside this file it more simple to setup

**Comment by am-i-dead** [comment]
> p12 it key format. not the openvpn setting format. Do you mean .ovpn ? For my understanding it should be just ovpn and keys should be inside this file it more simple to setup

at the moment we use .sswan and .mobileconf files to connect on different devices (.sswan for android and .mobileconf for osx/ios) and we need .p12 for linux and windows users. I guess it is already was generated when VPN servers were set up and we just have to make them downloadable. @the2pizza is working in this way, we will see tomorrow.

**Comment by er2805620** [comment]
With p12 key only. User should know lot of settings like server IP/address, port, chipers, type of connection etc
Better and more simple use all-in-one file for this with list of servers to connect

But need to check as minimum on Ubuntu and Windows as some options working only on Linux some only on WIndows like
dhcp-option DNS may not work on linux and need to add something like

```
up /etc/openvpn/update-resolv-conf
down /etc/openvpn/update-resolv-conf
```

**Basic example of ovpn file** 

```
client
dev tun
proto udp
sndbuf 0
rcvbuf 0
remote server1.mydomain
remote server2.mydomain
remote server3.mydomain
remote-random
resolv-retry 60
auth-nocache
remote-cert-tls server
cipher AES-256-CBC
resolv-retry infinite
nobind
persist-key
persist-tun
verb 0
auth-nocache

user nobody
group nobody

redirect-gateway def1
auth-nocache
script-security 2
dhcp-option DNS 1.1.1.1
dhcp-option DNS 8.8.4.4


<ca>
-----BEGIN CERTIFICATE-----
CA HERE
-----END CERTIFICATE-----
</ca>
<cert>
-----BEGIN CERTIFICATE-----
CERT HERE

</cert>
<key>
KEY HERE
-----END RSA PRIVATE KEY-----

</key>
#ONLY IF TLS AUTH used
tls-version-min 1.2
<tls-auth>
#
# 2048 bit OpenVPN static key
#
-----BEGIN OpenVPN Static key V1-----
30d659ce61111bc86b987262d6e626b5
b830dd01ce9bdd4599b0807130c954fa
954ee9e1aee0b67b8bf7db513c33bd28
e96d1201b42d601293e0eec7204f82b9
684299e0ec40c6522b9ed4f88c0f902c
ce6d6e4704c9fee53ad3ce7a06319a04
4032e88983b2386ce516b05115c46d1b
e868c4b4b3bc4968c9428c0aee07541f
89b8f5bd7d3d1c2c6cd766503b3180b5
febb478f0979d939546057d896fc3a28
9c1a4261b36355f052126c98c6df3d74
423dec346d1802ce6638b3b06e9d5042
72523da48fdeb20cdc1ed29342e16ce3
31b37871e04d5e1acaed38c58e7d6be7
12eaf56229f5c97a15c1e47006628526
38c5a871ad2d1d53e377dd4970923c69
-----END OpenVPN Static key V1-----
</tls-auth>

```

**Comment by am-i-dead** [comment]
> With p12 key only. User should know lot of settings like server IP/address, port, chipers, type of connection etc Better and more simple use all-in-one file for this with list of servers to connect
> 
> But need to check as minimum on Ubuntu and Windows as some options working only on Linux some only on WIndows like dhcp-option DNS may not work on linux and need to add something like
> 
> ```
> up /etc/openvpn/update-resolv-conf
> down /etc/openvpn/update-resolv-conf
> ```
> 
> **Basic example of ovpn file**
> 
> ```
> client
> dev tun
> proto udp
> sndbuf 0
> rcvbuf 0
> remote server1.mydomain
> remote server2.mydomain
> remote server3.mydomain
> remote-random
> resolv-retry 60
> auth-nocache
> remote-cert-tls server
> cipher AES-256-CBC
> resolv-retry infinite
> nobind
> persist-key
> persist-tun
> verb 0
> auth-nocache
> 
> user nobody
> group nobody
> 
> redirect-gateway def1
> auth-nocache
> script-security 2
> dhcp-option DNS 1.1.1.1
> dhcp-option DNS 8.8.4.4
> 
> 
> <ca>
> -----BEGIN CERTIFICATE-----
> CA HERE
> -----END CERTIFICATE-----
> </ca>
> <cert>
> -----BEGIN CERTIFICATE-----
> CERT HERE
> 
> </cert>
> <key>
> KEY HERE
> -----END RSA PRIVATE KEY-----
> 
> </key>
> #ONLY IF TLS AUTH used
> tls-version-min 1.2
> <tls-auth>
> #
> # 2048 bit OpenVPN static key
> #
> -----BEGIN OpenVPN Static key V1-----
> static key here
> -----END OpenVPN Static key V1-----
> </tls-auth>
> ```

**Comment by am-i-dead** [comment]
we need to give people access to VPN as fast as possible, if we can do it through ovpn - let's do it. 

But as I saw in https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md we need .p12 key for Windows and Linux users, and if I am right we already have this key on the server, we just need to publish it.

**Comment by er2805620** [comment]
yes, as ASAP option it ok.

BTW:  I thought we were talking about OpenVPN not about IPSEC ^-)

**Comment by am-i-dead** [comment]
> yes, as ASAP option it ok.
> 
> BTW: I thought we were talking about OpenVPN not about IPSEC ^-)

atm servers are based on ipsec

**Comment by theyllneverfindyourgrave** [comment]
done
