### ISSUE TITLE
[Doc] screencasts with instructions

### ISSUE THREAD

**Issue by the2pizza** [nezavisimost/FuckRKN1#81]
Currently we are working on moving instructions from GH Readme to a separate page and it will unlock limitation 10mb per video file. So we need more clear and good quality videos with instructions.

**Comment by lgklsv** [comment]
I guess it's better to create the instructions page first (like demo version) and right there take those screencasts. It's important because there should be downloadable files right on the page.

**Comment by HotFixDeveloper** [comment]
> I guess it's better to create the instructions page first (like demo version) and right there take those screencasts. It's important because there should be downloadable files right on the page.

https://github.com/nezavisimost/fuckrkn1.org - It's almost done and is in this repository

**Comment by HotFixDeveloper** [comment]
Moved - here - https://github.com/nezavisimost/fuckrkn1.org/issues/3
