### ISSUE TITLE
[Linux] Error while extracting certificates

### ISSUE THREAD

**Issue by mkost148** [nezavisimost/FuckRKN1#85]
`Downloads $ openssl pkcs12 -in vpnclient.p12 -cacerts -nokeys -out ikev2vpnca.cer
Enter Import Password:
Error outputting keys and certificates
40A7B959337F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:../crypto/evp/evp_fetch.c:349:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()
`

Ubuntu 22.04, strongswan installed, all are newest versions

**Comment by Nejjer** [comment]
Была такая же проблема. Добавь флажёк -legacy или --legacy

**Comment by mkost148** [comment]
Thanks!
