### ISSUE TITLE
[Doc] localization instructions page

### ISSUE THREAD

**Issue by the2pizza** [nezavisimost/FuckRKN1#86]
We need to find a way how to maintain only one page with code but for 2 language at least (RU,EN)

**Comment by nizhgo** [comment]
If we were using a framework, we could have an object with localization:

```
const lang = {
mainPageTitle: {
en: `Some english text`,
ru: `Some russian text`,
}
};
```
```
import lang from `....`

<h1 className={mainTitle}>{lang.mainPageTitle[{selectedLang}]}</h1>

….

```

**Comment by HotFixDeveloper** [comment]
Moved here - https://github.com/nezavisimost/fuckrkn1.org/issues/2
